python scripts/run_env.py \
--backend cpu \
--skip_avatar_animation \
--no_load_indoor_scene \
--scene NY \
--resolution 512 \
--num_agents 15 \
--config agents_num_15 \
--agent_type tour_agent \
--max_seconds 100 \
--save_per_seconds 1 \
--enable_gt_segmentation \
--logging_level info \
--overwrite